unit_app/urls.py
from django.urls import path
from .views import UnitView

urlpatterns = [
path('' , UnitView.as_view() , name = 'calculate_url')
]

unit_conv_project/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('unit_app.urls'))
]

unit_app/models.py
from django.db import models

# Create your models here.

unit_app/forms.py
from django import forms

class UnitForm(forms.Form):
    CHOICES  = [
        ('none' , 'Select Unit'),
        ('cm_m' , 'Centimetres to Metres' ),
        ('cm_inches' , 'Centimetres to Inches'),
        ('m_km' , 'Metres to Kilometres'),
        ('km_mi' , 'Kilometres to Miles'),
        ('g_kg' , 'Grames to Kilogrames'),
        ('kg_to' , 'Kilogrames to Tonnes')
    ]

    number = forms.FloatField(required=True)
    options = forms.ChoiceField(choices=CHOICES , required = True , label='options')


    def CalculateUnit(self):

        unit = self.cleaned_data['number']
        operation = self.cleaned_data['options']

        if operation == 'none':
            result = 'Please Try Again....'

        elif operation == 'cm_m':
            conversion = unit/1000
            result = f"{unit}cm = {conversion}metres"

        elif operation == 'cm_inches':
            conversion = unit/2.54
            result = f"{unit}cm = {conversion}inches"

        elif operation == 'm_km':
            conversion = unit/1000
            result = f"{unit}m = {conversion}km"

        elif operation == 'km_mi':
            conversion = unit*1.609
            result = f"{unit}km = {conversion}miles"

        elif operation == 'g_kg':
            conversion = unit/1000
            result = f"{unit}g = {conversion}kg"

        elif operation == 'kg_to':
            conversion = unit/1000
            result = f"{unit}kg = {conversion}tonnes"

        else:
            result = f"Error.\n Please Try Again"

        return result

unit_app/views.py
from django.views.generic import TemplateView , FormView
from .forms import UnitForm


class UnitView(FormView):
    form_class = UnitForm
    template_name = 'index.html'

    def form_valid(self, form):
        result = form.CalculateUnit()
        return self.render_to_response(self.get_context_data(form = form , result = result))

templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unit-Converter</title>
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
</head>
<body>
    <div class="container">
        <h1 class="1st-child">
                Unit-Converter
            </h1>
        <form action="" method="post">
        {%csrf_token%}
            <select name="options" id="id_options">
                {%for value , label in form.options.field.choices%}
                <option value="{{value}}" {%if form.options.value == value%}selected{%endif%}>{{label}}</option>
                {%endfor%}
            </select>    

            <input type="text" value="{{value.number.value|default:''}}" placeholder="Enter Number" name = "number">
            <button type="submit">Convert</button>            
        </form>
        
        <div class="results">
            {%if result%}
            <p>{{result}}</p>
            {%endif%}
        </div>
        
    </div>

    <script>


    </script>
</body>
</html>